### ISSUE TITLE
License, derivative work

### ISSUE THREAD

**Issue by MatMasIt** [jumpjack/greenpass#3]
I have made a derivative work of your repo which is user friendly, allowing direct scan-to-result data flow and bootstrap formatting.

The repo is: https://github.com/MatMasIt/green-pass-simple

It seems like no license has been specified for your code, so I will remove my repo if you request but if your intent was to make it open source I strongly advise using a license (Like MIT, or Apache2.0)

**Comment by jumpjack** [comment]
I don't understand anything about licences... Just do what you like with my code. :-)

**Comment by MatMasIt** [comment]
Thanks!
If that is your spirit, I suggest you to check out the "MIT" license.
It allows for everybody to use your code just in a chill way.
Just try creating a "LICENSE" file through the Github gui and select "Choose license", then complete the commit.

**Comment by jumpjack** [comment]
done, thanks for the hint.

**Comment by MatMasIt** [comment]
Well done
