### ISSUE TITLE
Non working code

### ISSUE THREAD

**Issue by lumb2019** [jumpjack/greenpass#5]
Hi,
I have a a lot of QR codes the Code is working with. But I have found one, the Script is not working for. The not working code is:

I have deleted it.

Are you able to help me find the issue with this?

Thanks a lot

Lars

**Comment by jumpjack** [comment]
Maybe a qr-decode failure, or a copy/paste failure? I cannot decode it with any decoder:
[Cyberchef recipe](https://gchq.github.io/CyberChef/#recipe=From_Hex('Auto')Zlib_Inflate(0,0,'Adaptive',false,false)To_Hex('Space',0)&input=Nzg5YzAxNjMwMTljZmVkMjg0NDNhMTAxN2Y2NmQ1YWJiYTY4YTk1ODI4MTA3OGI1ZDc4ZDM3YWNlMDc5Yjg5YWFiYmQ1Njc4MTJhYTU3MzBhMGI2NDk4Y2EzNTQ0OWQ0NzI0MjhiOWU5YmZiNzZiMzVlMzU5MDI5ODU0ODQyM2M1YjlmMjBlOGUwN2Y1YzE0OTAyOTI1ZDY3YzIxNTVhMWFiOTgwNzBlM2JjZTIzYmEyNzM5MjQ2OTI1ZmUxNTY4YjgxNTE0MDM0MmM1YTNiMTliZWYxY2UwZTA4NzljMjA0MmY1OWMyNWZmNDg3YWMwN2FlNWZkYWQwMTMwN2JmMzljZmZkNDBhOTVmZjljNGZhNzBhMWQ2OTFkMDUzYzg2NjRjNmQ0MDc3NjAxMmUwYjlkYmI3MGI5MDllNDYzNGI0ZGJhMjBiOGE3Yjg3YWU1MGE4MjI5NDVmNGJkMTFiZTRkOGY3YWI4NTdkYTAyMTEyZDhkZDEzNTZiNDhmZWI1NmI3NWQ0YmYwMjNmNTFjMzIxYzc5ZjQ4NGI0ODRkZWQ0ZjRkYTg2YzUxYzMyMWY0YzkxZTFjZTA5NzNhNTMzMmQ0MzIyMTEyZmUwN2RkYWU1M2EyMzI3MDljN2Y1NTEwNDAyNmZiOTM0NWE5MmI2OGEzZTIxYWYzNGMxYTFlZmM3NDZjNmVmODUxZTZmZjFiNDU1MDRjNGM0ODQxNTU0NTUyNjM2NzZlNzQ2NjRkNGY0ZTQ5NGI0MTYzNzY2NTcyNjUzMTJlMzAyZTMwNTg0MDQ4YTA4ZDMzYTNlZTJhMGIyMmM3MTNhNmRkM2UwYTZiOWU2NjYxOWQzNzc5YTI4Yzg4YzMxOTc4YWFjZTI0ODBhNjc2ZGFmMmU3YTcyOGFmZmVmODI5MWYwOTFmN2FjY2I5NzIzZjRjZDhmNzg2OTI0MDFkNDA4YjZhMzg0MmQ1MjFmOGNm)
[CBOR decoder](https://cbor.me/)

**Comment by jumpjack** [comment]
Base45 decoder:
https://dencode.com/string/base45

**Comment by lumb2019** [comment]
Hi and thank you.
If you make a QR code from the String for example here:
https://www.qrcode-generator.de
and scan with Compass Check App it will show that it is valid.
This is strange isn't it?

**Comment by lumb2019** [comment]
Sorry again:
If I decode on the page you give me:
https://dencode.com/string/base45
it seams to work...

**Comment by lumb2019** [comment]
There was an copy paste error, you are right. Here is the right Text from QR, that is working on the decode page but not in this script:

HC1:6BF+70790T9WJWG.FKY*4GO0RKPNHILCJ$VBFBBRW1*70HS8FN0WLCD/OWY01BCEKID97TK0F90KECTHGWJC0FDC:5AIA%G7X+AQB9746HS80:5AIBZ47VF6$A8VL6+0AP7BN46/46R46 463ZACN9+Y9 +AVK4WJCT3EHS8XJC$+DXJCCWENF6OF63W5NW6UF6%JC QE/IAYJC5LEW34U3ET7DXC9 QE-ED8%E.JCBECB1A-:8$966469L6OF6VX6Q$D.UDRYA 96NF6L/5SW6Y57KQEPD09WEQDD+Q6TW6FA7C466KCN9E%961A6DL6FA7D46JPCT3E5JDNA7$Q68465W51S6..DX%DZJC5/DL+8 VD 8D%$EWKEI3D:-C-3EWED1ECW.CBWEY*82T92694ZAVIAI3D8WE Y9G+95N9$PC5$CUZCY$5Y$527B789C%HQWK8E5%H4ZL2S/RS*UX51KUV:Q07WOK1DHBQZVQLTR4:1LPUR%CT M$MAW.85BNXQNF:JN408DJRP0HX48878CJD9K8BD4:F

**Comment by lumb2019** [comment]
There was an additionally copy paste error. 
This code is working on [decode.com](https://dencode.com/string/base45)
But not here.

HC1:6BF+70790T9WJWG.FKY*4GO0RKPNHILCJ$VBFBBRW1*70HS8FN0WLCD/OWY01BCEKID97TK0F90KECTHGWJC0FDC:5AIA%G7X+AQB9746HS80:5AIBZ47VF6$A8VL6+0AP7BN46/46R46 463ZACN9+Y9 +AVK4WJCT3EHS8XJC$+DXJCCWENF6OF63W5NW6UF6%JC QE/IAYJC5LEW34U3ET7DXC9 QE-ED8%E.JCBECB1A-:8$966469L6OF6VX6Q$D.UDRYA 96NF6L/5SW6Y57KQEPD09WEQDD+Q6TW6FA7C466KCN9E%961A6DL6FA7D46JPCT3E5JDNA7$Q68465W51S6..DX%DZJC5/DL+8 VD 8D%$EWKEI3D:-C-3EWED1ECW.CBWEY*82T92694ZAVIAI3D8WE Y9G+95N9$PC5$CUZCY$5Y$527B789C%HQWK8E5%H4ZL2S/RS*UX51KUV:Q07WOK1DHBQZVQLTR4:1LPUR%CT M$MAW.85BNXQNF:JN408DJRP0HX48878CJD9K8BD4:F

**Comment by lumb2019** [comment]
Hi,
here is a copy paste error, because in this testbed the sign "star" like * will be changed. So it is not possible to enter the code here. So I have added a text file. The right code is working on https://dencode.com/string/base45 but not here.
Thanks a lot
[QR.txt](https://github.com/jumpjack/greenpass/files/7723097/QR.txt)
.

**Comment by jumpjack** [comment]
```
HC1:6BF+70790T9WJWG.FKY*4GO0RKPNHILCJ$VBFBBRW1*70HS8FN0WLCD/OWY01BCEKID97TK0F90KECTHGWJC0FDC:5AIA%G7X+AQB9746HS80:5AIBZ47VF6$A8VL6+0AP7BN46/46R46 463ZACN9+Y9 +AVK4WJCT3EHS8XJC$+DXJCCWENF6OF63W5NW6UF6%JC QE/IAYJC5LEW34U3ET7DXC9 QE-ED8%E.JCBECB1A-:8$966469L6OF6VX6Q$D.UDRYA 96NF6L/5SW6Y57KQEPD09WEQDD+Q6TW6FA7C466KCN9E%961A6DL6FA7D46JPCT3E5JDNA7$Q68465W51S6..DX%DZJC5/DL+8 VD 8D%$EWKEI3D:-C-3EWED1ECW.CBWEY*82T92694ZAVIAI3D8WE Y9G+95N9$PC5$CUZCY$5Y$527B789C%HQWK8E5%H4ZL2S/RS*UX51KUV:Q07WOK1DHBQZVQLTR4:1LPUR%CT M$MAW.85BNXQNF:JN408DJRP0HX48878CJD9K8BD4:F
```

**Comment by lumb2019** [comment]
HC1:6BF+70790T9WJWG.FKY*4GO0RKPNHILCJ$VBFBBRW1*70HS8FN0WLCD/OWY01BCEKID97TK0F90KECTHGWJC0FDC:5AIA%G7X+AQB9746HS80:5AIBZ47VF6$A8VL6+0AP7BN46/46R46 463ZACN9+Y9 +AVK4WJCT3EHS8XJC$+DXJCCWENF6OF63W5NW6UF6%JC QE/IAYJC5LEW34U3ET7DXC9 QE-ED8%E.JCBECB1A-:8$966469L6OF6VX6Q$D.UDRYA 96NF6L/5SW6Y57KQEPD09WEQDD+Q6TW6FA7C466KCN9E%961A6DL6FA7D46JPCT3E5JDNA7$Q68465W51S6..DX%DZJC5/DL+8 VD 8D%$EWKEI3D:-C-3EWED1ECW.CBWEY*82T92694ZAVIAI3D8WE Y9G+95N9$PC5$CUZCY$5Y$527B789C%HQWK8E5%H4ZL2S/RS*UX51KUV:Q07WOK1DHBQZVQLTR4:1LPUR%CT M$MAW.85BNXQNF:JN408DJRP0HX48878CJD9K8BD4:F

**Comment by lumb2019** [comment]
If I insert it as it is you see the * will be changed.
But the code you inserted is the right one. 
Do you know, why it did not work in this Programm?

**Comment by jumpjack** [comment]
Now it's fixed.
